preprocess:
  # Define the preprocessing function
  input: data/raw/diabetes.csv
  output: data/preprocessed//diabetes.csv

train:
  data: data/raw/diabetes.csv
  model: models/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5